spring.application.name=TransportationBookingSystem_project


spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp

spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/resources/**


# Database connection URL
spring.datasource.url=jdbc:postgresql://localhost:5432/TransportationBookingSystem

# Database username
spring.datasource.username=postgres

# Database password
spring.datasource.password=7733

# PostgreSQL JDBC driver class name
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate dialect for PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Hibernate DDL auto-update setting (e.g., update, create, create-drop, validate, none)
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true